name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

defaults:
  run:
    shell: bash

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: allenevans/set-env@v2.0.0
        with:
          PATH: $GOPATH/bin:$PATH
      - run: go get golang.org/x/lint/golint
      - run: go get honnef.co/go/tools/cmd/staticcheck
      - run: sudo apt-get install libopenal-dev xorg-dev libgl1-mesa-dev -y --allow-unauthenticated
      - run: xvfb-run -a go test -v -race ./...
      - run: go vet ./...
      - run: staticcheck ./...
      - run: go build -v

  build_osx:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: allenevans/set-env@v2.0.0
        with:
          PATH: $GOPATH/bin:$PATH
      - run: go get golang.org/x/lint/golint
      - run: go get honnef.co/go/tools/cmd/staticcheck
      - run: brew install openal-soft
      - run: go test -v -race ./...
      - run: go vet ./...
      - run: staticcheck ./...
      - run: go build -v
