name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - run: go get golang.org/x/lint/golint
      - run: go get honnef.co/go/tools/cmd/staticcheck
      - run: sudo apt-get install libopenal-dev xorg-dev libgl1-mesa-dev -y --allow-unauthenticated
      - run: go test -v -race ./...
      - run: staticcheck ./...
